### ISSUE TITLE
pthread error

### ISSUE THREAD

**Issue by shark-oxi** [yorickdewid/Chat-Server#1]
Hi, I tried to compile your chat and I get this error : 
```
gcc Chat-Server/chat_server.c
/tmp/ccLRALL9.o: dans la fonction « hanle_client »:
chat_server.c:(.text+0xac9): référence indéfinie vers « pthread_detach »
/tmp/ccLRALL9.o: dans la fonction « main »:
chat_server.c:(.text+0xc85): référence indéfinie vers « pthread_create »
collect2: error: ld returned 1 exit status
```

this is strange because I can see `#include <pthread.h>` in your code.

**Comment by yorickdewid** [comment]
I'll look into it

**Comment by yorickdewid** [comment]
You'll need to link against the POSIX thread library. For convenience I'll create a makefile in the root

**Comment by shark-oxi** [comment]
Yes I did `gcc Chat-Server/chat_server.c -pthread` and it just worked fine.

**Comment by yorickdewid** [comment]
Either that or use GNU make
