### ISSUE TITLE
Protecting shared resources

### ISSUE THREAD

**Issue by intc** [yorickdewid/Chat-Server#6]
A couple of critical issues:

1. If I drop MAX_CLIENTS to 3 it'll allow only 2 connections.
2. Implementation uses threads but access to shared resources is not protected. Access to cli_count and clients array needs to be guarded by mutex locks so that only one thread can access the shared resource at time.

**Comment by yorickdewid** [comment]
1. Its just an off-by-one bug. Haven't fixed it, and its not that important. The define is just there to prevent massive numbers of threads (connections)
2.  True. This is really old code and it was never meant to be more than a testing stub. I spend a little while fixing the code and improving the quality. The counter now is an atomic integer and operations on the client array are put into critical sections guarded by a mutex.

There is numerous other issues requiring further improvement. The old stdlib is still using non-re-entrant functions and the proposed 'secure' alternatives aren't supported by all compilers as of yet. If C11 gains more ground I'd like to kick POSIX threads in lieu of `<threads.h>`

**Comment by intc** [comment]
Cool! =)
