### ISSUE TITLE
Issue with /nick command

### ISSUE THREAD

**Issue by strider-paff-shell** [yorickdewid/Chat-Server#7]
Hi, ive found an issue with the /nick command. The username is an char buffer with a len of 32 bytes. here is the possibility to write more than 32 bytes i can writer over the chunks at 96 bytes

**Comment by strider-paff-shell** [comment]
If /list is entered wo got a crash

**Comment by yorickdewid** [comment]
Thanks, fixed in 236edade9318465c076b5bca90dca1c2f6003500
